set dotenv-load := true

export PROFILE := "release"
alias b := build

default: build

build target="x86_64-unknown-linux-gnu":
    cargo build --profile {{PROFILE}} --target {{target}}

deploy host +args: build
    rsync -az target/{{host}} {{args}}

test *patterns:
    cargo test {{patterns}}
